### ISSUE TITLE
Not windows compatible?

### ISSUE THREAD

**Issue by wgaylord** [pfalcon/picotui#11]
Can you clarify if this is Windows compatible?

` but should work with any Python3 implementation which allows to access stdin/stdout file descriptors.`

My best guess would be no. But I don't want to start on a project just to figure out I have to start over.

**Comment by pfalcon** [comment]
As README explains, picotui requires VT100-compatible terminal which implements standard https://en.wikipedia.org/wiki/ANSI_escape_code . So, the question is not whether picotui Windows compatible, but whether Windows in ANSI terminal sequences compatible. If it is, picotui works. If it's not, picotui doesn't work. I don't use Windows (also MacOS, VMS, BeOS, etc.) and can't know. But note that MS-DOS in 1985 could do it with a proverbial ANSI.SYS, so likely a Windows users just need to know how to configure such support.

**Comment by AltoRetrato** [comment]
`picotui` uses the [tty](https://docs.python.org/3/library/tty.html) module, which in turn requires the [termios](https://docs.python.org/3/library/termios.html#module-termios) module that isn't available on Windows.

According to the [tty](https://docs.python.org/3/library/tty.html) page, "Because it [tty] requires the termios module, it will work only on Unix.".

**Comment by amotl** [comment]
Hi there,

by #36, `picotui` stops depending strictly on the `tty` or the `termios` modules. While I doubt it will work on Windows out of the box, there might be a way to follow now. Apart from that, @pfalcon's statements are absolutely true regarding VT100 and ANSI. However, if Windows does not yield appropriate support for that, things could be swapped accordingly.

Are you able to test the amended version on Windows, @AltoRetrato? I would love to hear about its outcome.

With kind regards,
Andreas.

**Comment by AltoRetrato** [comment]
Hi @amotl !

As @pfalcon stated, in the old days, ANSI.SYS in DOS would solve the problem, but it seems it is not compatible with modern versions of Windows (and/or it is a bit of a hassle to install it).

I tested your fork. Had to patch it a bit to make it run, though. At first there is no output at all, and after pressing [Ctrl]+[C] I see the raw escape sequences:

`[?9h[0;37;44m[2J[0m[?25l[7;7H                    [8;7H                    [9;7H                    [10;7H                    [11;7H                    [12;7H                    [13;7H                    [14;7H                    [15;7H                    [16;7H                    [6;6H┌────────────────────┐[17;6H└────────────────────┘[7;6H│ [...]`

But after adding these lines to the start of any example...

```python
import os
os.system("")
```

... I run the example again, had the same black screen, but after pressing [Ctrl]+[C] here's what I got:

![](https://i.imgur.com/dftZ62x.png)

It seems [Windows 10 supports ANSI/VT sequences since 2016](https://devblogs.microsoft.com/commandline/24-bit-color-in-the-windows-console/). Just don't ask me why we have to invoke `os.system("")` to activate it, though. You can see more details in [How to make win32 console recognize ANSI/VT100 escape sequences?](https://stackoverflow.com/questions/16755142/how-to-make-win32-console-recognize-ansi-vt100-escape-sequences)

Next I tried picotui (from `pip install picotui`). I still had to use `os.system("")` to enable ANSI support, but by just removing `tty` and `termios` imports it works better than your fork, displaying the widgets as expected. The keyboard navigation through the widgets works (as in I can use [Tab] to select a button and press [Enter] to activate it), but there are plenty of visual glitches (e.g., pressing [Tab] inserts spaces, pressing `arrow up` shows the history of the python console, ...).

I tested all examples and they all behave the same, except for `example_menu.py`  and `example_screen_resize.py`: they fail when `screen_size()` in `screen.py` uses the `select` module, which is also not completely supported on Windows ("On Windows, only sockets are supported; on Unix, all file descriptors.")

I also tested [Colorama](https://pypi.org/project/colorama/). It works a bit like the ANSI.SYS driver, and could provide better compatibility for more (all?) versions of Windows. I just had to change the `wr` method of `Screen` to use `print()` instead of `os.write()`. The examples behaved basically the same way, except Colorama can't convert some ANSI sequence correctly (cursor show / hide).

Without Colorama:
![Without Colorama](https://i.imgur.com/mBIEXHd.png)

With Colorama:
![With Colorama](https://i.imgur.com/aRjQjB6.png)

**Comment by amotl** [comment]
Hi Ricardo,

thanks for starting to work on bringing `picotui` to the native Windows environment and for sharing your outcome. This looks good!

So, rendering works fine and now it is just about making the keyboard handling work? Essentially, that's the very scope we have been working on and adjusted things appropriately thanks to @robert-hh's work on his MicroPython-Editor.

Most probably, `tty.setraw(0)` [1] is required to initialize the keyboard handling appropriately for the current implementation of the keycode handling. Detecting `<tab>` and `<enter>` is probably easy because it does not involve detecting the special keycodes required for other keys. Do `KEYUP` and `KEYDOWN` actually work for you?

In any case: Good that you are seeing progress with your experiments. It has been the same when I started to work on porting it to MicroPython. However, it took some more hours of efforts in order to make it really work as intended. Good luck with that!

With kind regards,
Andreas.

[1] https://github.com/pfalcon/picotui/blob/master/picotui/screen.py#L119-L123

**Comment by AltoRetrato** [comment]
IIRC, no navigation keys worked at all, including `KEYUP` and `KEYDOWN`.

I've been looking at a few TUI modules, and it seems there is no simple way to make multi-platform input. I tested asciimatics, and it works fine on Windows - but it uses [specific code for that platform](https://github.com/peterbrittain/asciimatics/blob/master/asciimatics/screen.py#L2006) (and [curses / termios for Unix](https://github.com/peterbrittain/asciimatics/blob/master/asciimatics/screen.py#L2192)).

**Comment by robert-hh** [comment]
I have tried using VT100 escape sequences with Windows 10, after activating it according to that link:
https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes It is surely not the only source of that information, but the first that worked for me. Controlling the screen is fine so far, but the keypad sequences are different. Below is a short list of key codes which I determined. There should be more. 
```
        KEYMAP = {
        "\x1b[H" : KEY_UP,
        "\x1b[\x8d": KEY_SHIFT_UP,
        "\x1b[P" : KEY_DOWN,
        "\x1b[\x91": KEY_SHIFT_DOWN,
        "\x1b[K" : KEY_LEFT,
        "\x1b[M" : KEY_RIGHT,
        "\x1b[G" : KEY_HOME, 
        "\x1b[O" : KEY_END, 
        "\x1b[I": KEY_PGUP,
        "\x1b[Q": KEY_PGDN,
        "\x1b[s": KEY_WORD_LEFT,
        "\x1b[t": KEY_WORD_RIGHT,
        "\x1b[S" : KEY_DELETE,
        "\x1b[\x94" : KEY_BACKTAB, ## Shift Tab
        "\x1b[w": KEY_FIRST, ## Ctrl-Home
        "\x1b[u": KEY_LAST, ## Ctrl-End
        "\x1b[\x93": KEY_DEL_WORD, ## Ctrl-Del
       }
```

**Comment by ibex-are-goats** [comment]
Hello all! Maybe this helps with getting picotui working on Windows: https://bugs.python.org/issue41663

**Comment by Gaming32** [comment]
So this works on Windows using colorama?
