### ISSUE TITLE
MacOSX terminal problems

### ISSUE THREAD

**Issue by tallforasmurf** [pfalcon/picotui#3]
This may well be an issue of lack of docs. Trying out on Python 3.4.3 on Mac OS. Run from the command line, widgets_demo produces approximately the right labels framed in a lot of a-with-circumflex, I'm guessing, escapes that didn't? Possibly I don't have my Terminal options set right, but no info on what's needed.

If I step through widgets_demo in Wing IDE, line 183 of screen.py, `cls.org_termios = termios.tcgetattr(0)` traps out with `termios.error: (25, 'Inappropriate ioctl for device')`, and the run goes straight to the finally: clause. I could speculate that this is due to the Wing IDE stdout/stderr window again not configured as expected. But that would be...?

**Comment by pfalcon** [comment]
picotui is intended to be used on a pristine POSIX terminal, so yes, any IDE would be a first suspect.

**Comment by tallforasmurf** [comment]
OK forget the IDE, I tell the Mac OS Terminal app it is to "declare as a vt100" which is the only preference setting I can find that might affect the decoding of escapes, size it to 80x25, and run the test prog.

<img width="490" alt="ptui" src="https://cloud.githubusercontent.com/assets/1137018/17988011/3929d876-6ad8-11e6-8218-2bd30a62ab06.png">
googling around a bit I cannot find any documentation on the emulation used by Terminal.app.

**Comment by pfalcon** [comment]
Well, picotui requires terminal with utf-8 support for line-drawing characters. Based on the screenshot above, your terminal is not in utf-8 mode (but 8-bit charset mode perhaps). I don't use MacOS, so unfortunately can't say what to do. I'd check all the settings in menu, and tried to read manual/google a bit more.

**Comment by tallforasmurf** [comment]
Aha. I set Terminal Preferences to encoding:utf-8 and now I get proper appearance:
<img width="736" alt="ptui2" src="https://cloud.githubusercontent.com/assets/1137018/18011144/a9361aae-6b68-11e6-9c36-b8395c502a6f.png">
I can navigate with up/down arrows and tab/shift-tab, and select with return. I could edit text fields as you see.

The only colors are shown (no red). The Frame behaved oddly, I could not affect the radio buttons.

It does not respond to mouse clicks -- should it? (Ordinarily, Terminal windows support the mouse for click/drag selection of displayed text.)

**Comment by tallforasmurf** [comment]
Further thought: since you don't have a Mac to develop on, I will maintain suitably low expectations for this. I don't have any need for it, just poking it for fun.

At some future time I might look at the code and see if I can see anything, if so might come up with a pull request.

**Comment by pfalcon** [comment]
Mouse is supported, but requires Xterm-compatible terminal. Again, no idea how to do that on Mac (but Xterm is essentially the only way to support mouse in a POSIX terminal, so it should be supported, juts may need to figure how to enable it).

Some widgets don't implement so far interaction both by mouse and keyboard, I'm waiting for bugreports from someone who cares ;-) (I don't much so far, I have both kbd and mouse and can switch easily).

Other artifact I see from your screenshot is that I don't set attributes explicitly in some places, assuming Ubuntu's default of black-on-white, and that's not good, attrs should be set explicitly.

Vertical gaps are due to font (or other terminal settings). I had similar issue on Ubuntu, until I switched to a different terminal font, as explained at the bottom of README.
