### ISSUE TITLE
Partial docstrings

### ISSUE THREAD

**Issue by piyueh** [pfalcon/picotui#45]
Hi, thanks for this tool. I'm reading the source code to understand how it works. I've learned a lot about terminal control sequences.

At the same time, I added docstrings to the code when (I think) I understood the functionality or goal of a piece of code. Just wondering, will you be interested in merging back the docstrings? If you would like, I can make a pull request. The current state of the docstring is in [this branch](https://github.com/piyueh/picotui/tree/docstring).

Though, I don't think I'll add docstring to all classes/functions. I only add docstring to those I want to read and understand.

**Comment by pfalcon** [comment]
Thanks for your interest in the project.

There're however a number of concerns with the proposed changes:

1. Picotui is explicitly intended to be used with https://github.com/pfalcon/pycopy, which is intended for very small systems, where there's no extra space for nice to have, but not exactly required things, like docstrings.
2. Picotui is generally a minimalist project, with very obvious criteria: "the smaller the source code, the better". Growing it with (long) docstrings goes against that aim.
3. Picotui is very simple project with simple code. You can judge that by yourself - yesterday you knew nothing about it, and today you have a bunch of detailed docstrings written. The point is, other people can easily do that (figure out how it works) even without docstrings. There's a well-established paradigm of "the source code is the best documentation" (https://wiki.c2.com/?UseTheSourceLuke). Of course, that works much better when the code is simple and small, rather than when it's sized in megabytes. That's why I'm keen to uphold smallness and simplicity of the code.
4. Finally, anything added to picotui increases my maintenance burden. To merge your changes, I would need to spend time to review them, to make sure they don't contain wrong information, have suitable formatting, don't have typos, etc. Then I'll need to make sure I update them if I change code. I'll need to make sure that if someone else changes code, they update docstring. I'll need to answer questions about docstrings. Etc, etc. I'm sorry, but my time is very limited. I have dozens of projects, and picotui is very simple among them. I have projects, where docstrings (and comments/docs) are *really* needed. I'd rather spend my time on such cases.

**Comment by piyueh** [comment]
That makes sense. Thanks again for open-sourcing the code!
